name: IBM Cloud Auto Restart

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 7 * * THU'

jobs:
  ibm-cloud-restart:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Init
      run: |
        chmod -R 777 ./IBM_Cloud_CLI/
        ./IBM_Cloud_CLI/ibmcloud config --check-version=false
    - name: Login IBM Cloud
      env:
        IBM_ACCOUNT: ${{ secrets.IBM_ACCOUNT }}
        REGION_NUM: ${{ secrets.REGION_NUM }}
      run: |
        ./IBM_Cloud_CLI/ibmcloud login --apikey  $IBM_ACCOUNT -r us-south
    - name: Target IBM Cloud
      env:
        RESOURCE_ID: ${{ secrets.RESOURCE_ID }}
        REGION_NUM: ${{ secrets.REGION_NUM }}
      run: |
        ./IBM_Cloud_CLI/ibmcloud target -g "$RESOURCE_ID" -r us-south 
        ./IBM_Cloud_CLI/ibmcloud cf install -f -v 6.15.0
    - name: Restart IBM Cloud
      env:
        IBM_APP_NAME: ${{ secrets.IBM_APP_NAME }}
        RESOURCE_ID: ${{ secrets.RESOURCE_ID }}
        REGION_NUM: ${{ secrets.REGION_NUM }}
        IBM_ORG: ${{ secrets.IBM_ORG }}
        IBM_SPACE: ${{ secrets.IBM_SPACE }}  
      run: |
        ./IBM_Cloud_CLI/ibmcloud target -cf -o "$IBM_ORG" -s "$IBM_SPACE"
        ./IBM_Cloud_CLI/ibmcloud cf restart "$IBM_APP_NAME"


